server:
  port: 8080
  servlet:
    context-path: /

logging.level.org.springframework.boot.autoconfigure: ERROR

spring:
  # thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML
  # druid
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/emall?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8
    username: jason
    password: 123456

    filters: stat,wall,log4j
    maxActive: 2
    initialSize: 1
    # 配置获取连接等待超时的时间
    maxWait: 60000
    minIdle: 1
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

  # redis
  redis:
    host: 192.168.153.129
    port: 6379
    # 客户端超时时间
    timeout: 3000
    password: 123456
    # 最大连接数
    poolMaxTotal: 10
    # 最大空闲数
    poolMaxIdle: 10
    # 最大建立连接等待时间
    poolMaxWaitMillis: 3000

# mybatis
mybatis:
  type-aliases-package: com.emall.dao
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:mappers/*.xml

#shiro
shiro:
  enabled: true
  password:
    algorithmName: sha-256
    hashIterations: 1024
