server:
  port: 8888
  servlet:
    context-path: /

logging.level.org.springframework.boot.autoconfigure: ERROR

spring:
  # druid
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.153.130:3306/emall?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8
    username: jason
    password: 123456

    filters: stat,wall,log4j
    maxActive: 1000
    initialSize: 1
    # 配置获取连接等待超时的时间
    maxWait: 60000
    minIdle: 300
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

  # redis
  redis:
    host: 192.168.153.130
    port: 6379
    # 客户端超时时间
    timeout: 3000
    password: 123456
    # 最大连接数
    poolMaxTotal: 1000
    # 最大空闲数
    poolMaxIdle: 500
    # 最大建立连接等待时间
    poolMaxWaitMillis: 3000

  # rabbitmq
  rabbitmq:
    host: 192.168.153.130
    port: 5672
    username: jason
    password: 123456
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1
    publisher-confirms: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
      enabled: true

# mybatis
mybatis:
  type-aliases-package: com.emall.dao
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:mappers/*.xml

#shiro
shiro:
  enabled: true
